# Generated by Django 4.0.3 on 2022-04-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Memory',
        ),
    ]
