# Generated by Django 4.0.3 on 2022-04-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_rename_product_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='price',
        ),
        migrations.AddField(
            model_name='memory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='species',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
