# Generated by Django 4.0.3 on 2022-04-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_remove_memory_image_remove_memory_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='thumbnail',
            new_name='photo',
        ),
    ]
