# Generated by Django 4.0.3 on 2022-04-04 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memory', '0005_alter_memory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memory',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='memory',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
